// with-nextjs/src/app/page.tsx
"use client";
import { useState } from "react";
import { capsuleClient } from "@/client/capsule";
import { CapsuleModal, OAuthMethod } from "@usecapsule/react-sdk";
import "@usecapsule/react-sdk/styles.css";
import Logo from "./capsule-logo.svg";

export default function Home() {
  const [isModalOpen, setIsModalOpen] = useState(false);

  return (
    <div style={{ textAlign: "center", marginTop: "50px" }}>
      <h1>Capsule Modal Starter Template with Next.js</h1>
      <button
        onClick={() => setIsModalOpen(true)}
        style={{ padding: "10px 20px", fontSize: "16px", cursor: "pointer" }}>
        Open Capsule Modal
      </button>
      <CapsuleModal
        capsule={capsuleClient}
        appName="Capsule Modal Starter Template"
        logo={Logo.src}
        disableEmailLogin={false}
        disablePhoneLogin={false}
        oAuthMethods={Object.values(OAuthMethod)}
        isOpen={isModalOpen}
        onClose={() => setIsModalOpen(false)}
        onRampTestMode={true}
        twoFactorAuthEnabled={false}
      />
    </div>
  );
}

// with-svelte-vite/src/App.svelte
<script lang="ts">
  import { CapsuleModal, OAuthMethod } from "@usecapsule/react-sdk";
  import "@usecapsule/react-sdk/styles.css";
  import Logo from "./assets/capsule-logo.svg";
  import { capsuleClient } from "./client/capsule";
  import { sveltify } from "svelte-preprocess-react";

  const react = sveltify({ CapsuleModal });
  let isModalOpen = false;
</script>

<div class="container">
  <h1>Capsule Modal Starter Template with Svelte Kit</h1>
  <button on:click={() => isModalOpen = true}>
    Open Capsule Modal
  </button>
  <react.CapsuleModal
    capsule={capsuleClient}
    appName="Capsule Modal Starter Template"
    logo={Logo}
    disableEmailLogin={false}
    disablePhoneLogin={false}
    oAuthMethods={Object.values(OAuthMethod)}
    isOpen={isModalOpen}
    onClose={() => isModalOpen = false}
    onRampTestMode={true}
    twoFactorAuthEnabled={false}
  />
</div>

<style>
  .container {
    text-align: center;
    margin-top: 50px;
  }

  button {
    padding: 10px 20px;
    font-size: 16px;
    cursor: pointer;
  }
</style>
